# Generated by Django 3.2.7 on 2021-12-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_Ocr_Note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr_note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ocr_note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.customer'),
        ),
    ]
