# Generated by Django 3.2.7 on 2021-12-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_Ocr_Note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocr_note',
            old_name='user',
            new_name='ocr_user',
        ),
    ]
