# Generated by Django 3.2.7 on 2021-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_Ocr_Note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr_note',
            name='ocr_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ocr'),
        ),
    ]
